import 'dart:io';

void main() async {
  final file = File('lib/core/isar_models.g.dart');
  if (!await file.exists()) {
    print('Error: lib/core/isar_models.g.dart not found.');
    exit(1);
  }

  print('Patching Isar generated code for Web JS integer precision compatibility...');
  
  String content = await file.readAsString();

  // Mapping of exact 64-bit integer values generated by Isar that cause dart2js compile errors
  // to their bitwise-shift equivalents that compile cleanly on JS.
  final replacements = {
    '8174210821231210712': '(1903206766 << 32) | 3735285976',
    '-3268401673993471357': '(3533983230 << 32) | 2253634179',
    '-5727176259899839698': '(2961505161 << 32) | 379497262',
    '-4589044699189655650': '(3226497064 << 32) | 3999877022',
  };

  int count = 0;
  replacements.forEach((target, replacement) {
    if (content.contains(target)) {
      content = content.replaceAll(target, replacement);
      count++;
    }
  });

  if (count > 0) {
    await file.writeAsString(content);
    print('Successfully applied $count patches to lib/core/isar_models.g.dart.');
  } else {
    print('No patches needed or code already patched.');
  }
}
